---
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  #array-callback-return: error
  arrow-body-style:
    - off
    - as-needed
    - requireReturnForObjectLiteral: true
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  arrow-spacing: error
  #block-scoped-var: error
  block-spacing:
    - error
    - always
  brace-style: error
  #callback-return: error
  camelcase:
    - error
    - properties: never
  #class-methods-use-this: error
  comma-dangle:
    - error
    - never
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  complexity:
    - off
    - max: 18
  computed-property-spacing:
    - error
    - never
  #consistent-this: ??
  #consistent-return: ??
  #constructor-super: ??
  curly:
    - error
    - multi-line
  default-case: off
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last:
    - error
    - unix
  eqeqeq: off
  #func-name-matching: error
  #func-names: warn
  #func-style: ??
  generator-star-spacing:
    - error
    - after: true
      before: false
  global-require: off
  #guard-for-in: error
  #handle-callback-err: ??
  #id-blacklist:
    #- error
    #- cb
    #- e
  #id-length: 2
  id-match: off
  indent:
    - error
    - 4
    - SwitchCase: 1
      VariableDeclarator: 1
  #init-declarations: error
  jsx-quotes: off
  key-spacing:
    - error
    - afterColon: true
      beforeColon: false
      mode: minimum
  keyword-spacing: error
  #line-comment-position: error
  linebreak-style:
    - error
    - unix
  #lines-around-comment: ??
  #lines-around-directive: error
  max-depth:
    - error
    - 5
  max-len:
    - error
    - 250
  #max-lines:
    #- error
    #- 400
  #max-nested-callbacks: ??
  #max-params: ??
  #max-statements-per-line: ??
  #max-statements: ??
  #multiline-ternary:
    #- error
    #- never
  #new-cap:
    #- error
    #- capIsNew: false
      #newIsCap: false
      #properties: true
  #new-cap: 0
  new-parens: error
  #newline-before-return: ??
  #newline-per-chained-call: ??
  #no-alert: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-case-declarations: error
  no-catch-shadow: error
  #no-class-assign: ??
  no-cond-assign:
    - error
    - always
  no-confusing-arrow: error
  #no-console: error
  #no-const-assign: ??
  no-constant-condition: error
  #no-continue: ??
  no-control-regex: error
  no-debugger: error
  no-delete-var: error
  no-div-regex: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-character-class: error
  no-empty-function:
    - error
    - allow:
      - functions
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extend-native: error
  no-extra-bind: warn
  no-extra-parens:
    - error
    - functions
  no-extra-semi: error
  no-fallthrough:
    - error
    - commentPattern: "[\\s\\w]"
  no-floating-decimal: error
  no-func-assign: error
  no-global-assign: error
  #no-inline-comments: ??
  no-implicit-coercion:
    - error
    - allow:
      - '!!'
  no-implicit-globals: error
  no-implied-eval: error
  #no-inner-declarations: error
  no-invalid-regexp: error
  #no-invalid-this: off
  no-irregular-whitespace: error
  #no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  #no-loop-func: error
  no-magic-numbers: off
  #no-mixed-operators:
    #- error
    #- allowSamePrecedence: true
  no-mixed-requires:
    - error
    - allowCall: false
      grouping: false
  no-mixed-spaces-and-tabs: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxBOF: 0
      maxEOF: 0
  #no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  #no-new: error
  #no-new-func: error
  #no-new-object: error
  #no-new-require: ??
  #no-new-symbol: ??
  no-new-wrappers: error
  no-obj-calls: error
  no-octal: error
  no-octal-escape: error
  #no-params-reassign: off
  no-path-concat: error
  #no-plusplus: ??
  #no-process-env: ??
  #no-process-exit: error
  no-proto: error
  #no-redeclare: error
  no-regex-spaces: error
  no-restricted-globals: error
  #no-restricted-imports: ??
  #no-restricted-modules: ??
  no-restricted-properties: error
  #no-restricted-syntax: ??
  #no-return-assign: error
  no-return-await: error
  #no-script-url: error
  no-self-assign: error
  no-self-compare: error
  #no-sequences: error
  #no-shadow: ??
  #no-shadow-restricted-names: error
  #no-spaced-func: error
  no-sparse-arrays: error
  #no-sync: ??
  no-tabs: error
  #no-ternary: ??
  #no-this-before-super: ??
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef:
    - error
    - typeof: false
  no-undef-init: error
  #no-undefined: error
  #no-underscore-dangle: off
  #no-unexpected-multiline: error
  no-unmodified-loop-condition: error
  #no-unneeded-ternary: ??
  no-unreachable: error
  no-unsafe-negation: error
  no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: false
  no-unused-labels: error
  no-unused-vars:
    - error
    - args: none
  no-use-before-define: off
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename:
    - error
    - ignoreDestructuring: false
      ignoreImport: false
      ignoreExport: false
  no-useless-return: error
  no-var: error
  no-void: error
  #no-warning-comments: error
  #no-with: error
  no-whitespace-before-property: error
  object-curly-newline:
    - error
    - consistent: true
      multiline: true
  object-curly-spacing:
    - error
    - always
  #object-property-newline: ??
  #object-shorthand: ??
  #one-var-declaration-per-line: ??
  #one-var: ??
  #operator-assignment: ??
  #operator-linebreak: ??
  #padded-blocks: ??
  #padding-line-between-statements:
    #- error
    #-
      #- blankLine: never
        #next: *
        #prev: break
      #- blankLine: never
        #next: *
        #prev: if
      #- blankLine: never
        #next: *
        #prev: switch
      #- blankLine: never
        #next: *
        #prev: try
      #- blankLine: never
        #next: *
        #prev: while
  #prefer-arrow-callback: error
  prefer-const: error
  #prefer-destructuring: error
  prefer-promise-reject-errors: error
  #prefer-rest-params: ??
  prefer-spread: error
  #prefer-template: ??
  #quote-props: ??
  #quotes: off
  radix:
    - error
    - as-needed
  require-await: error
  #require-jsdoc: ??
  #require-yield: ??
  #rest-spread-spacing: ??
  semi-spacing:
    - error
    - after: true
      before: false
  semi:
    - off
    - never
  #soft-vars: ??
  sort-keys: off
  #sort-imports: ??
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  #space-in-parens: ??
  space-infix-ops: off
  space-unary-ops: off
  #spaced-comment: ??
  #symbol-description: error
  strict: error
  #template-curly-spacing: ??
  template-tag-spacing: error
  use-isnan: error
  valid-jsdoc:
    - off
    -
      prefer:
        arg: param
        argument: param
        class: constructor
        return: return
        virtual: abstract
      #matchDescription: '.+' # match any text
      preferType:
        array: array
        object: object
      requireParamDescription: false
      requireReturn: false
      requireReturnDescription: false
      requireReturnType: true
  valid-typeof: error
  vars-on-top: off
  wrap-iife: error
  #wrap-regex: ??
  #yield-star-spacing: ??
  #yoda: error
